### ISSUE TITLE
default redux action/promise handler

### ISSUE THREAD

**Issue by enapupe** [CheesecakeLabs/react-redux-boilerplate#18]
we should probably add `redux-promise-middleware` to our devDependencies and adopt it as a  default way of handling that async stuff. The `error` and `loading` reducers also seem to be a good standard.. Right now the boilerplate has no async actions, but it might worth adding some..

**Comment by enapupe** [comment]
Mind adding that stuff when you plug in `fetchy`?

**Comment by dleitee** [comment]
There is the Github API `https://api.github.com/users/<username>`. 

It's a simple and open API.
