### ISSUE TITLE
Move services to inside each module

### ISSUE THREAD

**Issue by smaniotto** [CheesecakeLabs/react-redux-boilerplate#38]
What do you think about bringing the services folder to inside each module? I think they will always be coupled to one module.

```
└ modules/
   └ actions.js
   └ reducers.js
   └ services.js
```

**Comment by enapupe** [comment]
I have a few exceptions on woovit. I think there's no big gain in doing so.
Maybe I'm the exception to the rule..  
@dleitee does that apply to MnH?

**Comment by smaniotto** [comment]
@enapupe updated my comment. What's your exception? Do you use the same service in different modules?

**Comment by enapupe** [comment]
Yes. Same service being imported in different modules.

**Comment by smaniotto** [comment]
That happens also when reducers in different modules respond to the same action. What do you do 
 normally? Import the action constant in the other module reducer?

**Comment by enapupe** [comment]
Yes.

**Comment by dleitee** [comment]
> What do you think about bringing the services folder to inside each module? I think they will always be coupled to one module.

I have a lot of exceptions on MnH. Example: doctor's service is used on doctor's module and appointment's module.

**Comment by enapupe** [comment]
I'm closing this, if anyone has another argument please reopen.
